"""Self-contained reports — HTML match reports & teaming briefs + CSV/JSON.

Every HTML artifact is a single file with inline CSS and **no JavaScript, no CDN
dependency, no external asset** — it renders offline, air-gapped, and pastes
cleanly into an email or a data room. All values are HTML-escaped.

Exports:
  * ``match_report_html``  — ranked capital matches with per-match factor bars.
  * ``teaming_brief_html`` — a recommended team, coverage, and gap analysis.
  * ``matches_csv`` / ``matches_json`` — machine-readable match export.
  * ``team_json``          — machine-readable teaming recommendation.

SCOPE: business reporting only.
"""
from __future__ import annotations

import csv
import html
import io
import json
from typing import Any

from .matching import MatchResult
from .teaming import Opportunity, Org, TeamRecommendation


def _esc(x: Any) -> str:
    return html.escape(str(x), quote=True)


_STYLE = """
:root{--ink:#1a202c;--mut:#718096;--pur:#6b46c1;--blu:#2b6cb0;--bg:#f7fafc;--line:#e2e8f0}
*{box-sizing:border-box}body{margin:0}
.wrap{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:var(--ink);
  max-width:960px;margin:0 auto;padding:28px 22px;line-height:1.5}
h1{font-size:26px;margin:0 0 2px}h2{font-size:18px;margin:26px 0 10px;border-bottom:2px solid var(--line);padding-bottom:6px}
.sub{color:var(--mut);margin:0 0 18px;font-size:14px}
.card{border:1px solid var(--line);border-radius:10px;padding:16px 18px;margin:12px 0;background:#fff}
.hd{display:flex;justify-content:space-between;align-items:baseline;gap:12px;flex-wrap:wrap}
.score{font-size:22px;font-weight:700}
.band{font-size:12px;text-transform:uppercase;letter-spacing:.05em;padding:2px 9px;border-radius:999px;color:#fff}
.strong{background:#276749}.promising{background:var(--blu)}.possible{background:#b7791f}.weak{background:#9b2c2c}
table{border-collapse:collapse;width:100%;font-size:14px}
th,td{text-align:left;padding:7px 10px;border-bottom:1px solid var(--line);vertical-align:top}
th{color:var(--mut);font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:.03em}
.bar{height:9px;border-radius:5px;background:var(--line);overflow:hidden;min-width:90px}
.bar>span{display:block;height:100%;background:linear-gradient(90deg,var(--pur),var(--blu))}
.mut{color:var(--mut)}.chip{display:inline-block;background:var(--bg);border:1px solid var(--line);
  border-radius:6px;padding:1px 7px;margin:1px;font-size:12px}
.abst{opacity:.55;font-style:italic}
.foot{margin-top:30px;color:var(--mut);font-size:12px;border-top:1px solid var(--line);padding-top:12px}
.ok{color:#276749;font-weight:600}.no{color:#9b2c2c;font-weight:600}
.tbl-scroll{overflow-x:auto}
"""


def _page(title: str, body: str) -> str:
    return (
        "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">"
        "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
        f"<title>{_esc(title)}</title><style>{_STYLE}</style></head>"
        f"<body><div class=\"wrap\">{body}"
        "<div class=\"foot\">Generated by dealflow — offline, self-contained "
        "(no JavaScript, no external assets). Part of the Cognis Neural Suite.</div>"
        "</div></body></html>"
    )


def _bar(pct: float) -> str:
    p = max(0.0, min(100.0, pct))
    return f'<div class="bar"><span style="width:{p:.0f}%"></span></div>'


# --------------------------------------------------------------------------- #
# Match report
# --------------------------------------------------------------------------- #
def match_report_html(company: str, matches: list[MatchResult]) -> str:
    """A ranked capital-match report for one company, factors shown as bars."""
    cards = []
    for m in matches:
        rows = []
        for f in sorted(m.factors, key=lambda x: x.weight, reverse=True):
            if f.abstained:
                rows.append(
                    f'<tr class="abst"><td>{_esc(f.name)}</td><td class="mut">w {f.weight:.1f}</td>'
                    f'<td colspan="2">abstained — {_esc(f.reason)}</td></tr>'
                )
            else:
                pct = (f.raw or 0.0) * 100
                rows.append(
                    f"<tr><td>{_esc(f.name)}</td><td class=\"mut\">w {f.weight:.1f}</td>"
                    f"<td>{_bar(pct)}</td><td>{pct:.0f}% — {_esc(f.reason)}</td></tr>"
                )
        cards.append(
            f'<div class="card"><div class="hd">'
            f'<div><strong>{_esc(m.source)}</strong> '
            f'<span class="mut">{_esc(m.source_meta.get("category") or "")}</span></div>'
            f'<div><span class="score">{m.score:.0f}</span>'
            f'<span class="mut">/100</span> '
            f'<span class="band {m.band}">{m.band}</span></div></div>'
            f'<div class="tbl-scroll"><table><thead><tr><th>factor</th><th>weight</th>'
            f'<th>match</th><th>why</th></tr></thead><tbody>{"".join(rows)}</tbody></table></div></div>'
        )
    body = (
        f"<h1>Capital match report</h1>"
        f'<p class="sub">{_esc(company)} · {len(matches)} source(s) scored · '
        f"ranked by explainable fit</p>"
        f"{''.join(cards) if cards else '<p class=\"mut\">No matches.</p>'}"
    )
    return _page(f"Match report — {company}", body)


def matches_csv(matches: list[MatchResult]) -> str:
    cols = ["company", "source", "score", "band", "top_factors"]
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=cols, lineterminator="\n")
    w.writeheader()
    for m in matches:
        tops = "; ".join(f"{f.name}={((f.raw or 0)*100):.0f}%" for f in m.top_factors(3))
        w.writerow({
            "company": m.company, "source": m.source,
            "score": f"{m.score:.2f}", "band": m.band, "top_factors": tops,
        })
    return buf.getvalue().rstrip("\n")


def matches_json(matches: list[MatchResult]) -> str:
    return json.dumps({"matches": [m.to_dict() for m in matches]}, indent=2)


# --------------------------------------------------------------------------- #
# Teaming brief
# --------------------------------------------------------------------------- #
def teaming_brief_html(rec: TeamRecommendation, opp: Opportunity, orgs: dict[str, Org]) -> str:
    """A one-page teaming brief: the team, coverage, gaps, and rationale."""
    member_rows = []
    for oid in rec.members:
        o = orgs.get(oid)
        if not o:
            continue
        caps = "".join(f'<span class="chip">{_esc(c)}</span>' for c in sorted(o.capabilities))
        sas = "".join(f'<span class="chip">{_esc(s)}</span>' for s in sorted(o.set_asides)) or '<span class="mut">—</span>'
        tag = " (prime)" if oid == rec.prime else ""
        member_rows.append(
            f"<tr><td><strong>{_esc(o.name)}</strong>{tag}<br>"
            f'<span class="mut">{_esc(o.role)}</span></td>'
            f"<td>{caps}</td><td>{sas}</td></tr>"
        )
    cov_pct = rec.coverage * 100
    uncovered = "".join(f'<span class="chip">{_esc(c)}</span>' for c in sorted(rec.uncovered)) or '<span class="ok">all covered</span>'
    sa_missing = "".join(f'<span class="chip">{_esc(c)}</span>' for c in sorted(rec.set_asides_missing)) or '<span class="ok">all goals met</span>'
    rationale = "".join(f"<li>{_esc(r)}</li>" for r in rec.rationale)
    complete = not rec.uncovered and not rec.set_asides_missing
    verdict = '<span class="ok">complete team</span>' if complete else '<span class="no">gaps remain</span>'
    body = (
        f"<h1>Teaming brief</h1>"
        f'<p class="sub">{_esc(opp.name)} · required-capability coverage '
        f"{cov_pct:.0f}% · {verdict}</p>"
        f"<h2>Recommended team</h2>"
        f'<div class="tbl-scroll"><table><thead><tr><th>organization</th><th>capabilities</th>'
        f"<th>set-asides</th></tr></thead><tbody>{''.join(member_rows)}</tbody></table></div>"
        f"<h2>Coverage &amp; gap analysis</h2>"
        f'<div class="card"><table>'
        f"<tr><td>Required coverage</td><td>{_bar(cov_pct)}</td><td>{cov_pct:.0f}%</td></tr>"
        f"<tr><td>Uncovered requirements</td><td colspan=\"2\">{uncovered}</td></tr>"
        f"<tr><td>Unmet set-aside goals</td><td colspan=\"2\">{sa_missing}</td></tr>"
        f"</table></div>"
        f"<h2>Rationale</h2><ol>{rationale}</ol>"
    )
    return _page(f"Teaming brief — {opp.name}", body)


def team_json(rec: TeamRecommendation) -> str:
    return json.dumps(rec.to_dict(), indent=2)
